server:
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          type: trace
          use_sql_comments: true
          format_sql: true
          show_sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/tiki-dev
    username: postgres
    password: link@SS2020!
    driverClassName: org.postgresql.Driver
